[package]
name = "trillium-cli"
version = "0.0.10"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"
description = "the trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
ansi-to-html = "0.1.0"
async-channel = "1.6.1"
async-fs = "1.5.0"
async-global-executor = "2.0.2"
async-io = "1.6.0"
atty = "0.2.14"
blocking = "1.0.2"
broadcaster = "1.0.0"
env_logger = "0.8.4"
futures-lite = "1.12.0"
log = "0.4.14"
serde = "1.0.126"
serde_json = "1.0.64"
structopt = "0.3.22"
trillium = "^0.1.0"
trillium-native-tls = "0.1.0"
trillium-rustls = "0.1.0"
trillium-proxy = "0.1.0"
trillium-router = "0.2.0"
trillium-static = { version = "0.1.0", features = ["smol"] }
trillium-websockets = { version = "0.1.1", features = ["json"] }
trillium-smol = "0.1.2"
trillium-client = "0.1.0"
trillium-logger = "0.1.2"
trillium-html-rewriter = "0.1.0"

[dependencies.bat]
version = "0.18.1"
default-features = false
features = [
  "atty",
  "clap",
  "dirs-next",
  "lazy_static",
  "paging",
  "wild",
  "regex-onig",
]

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.9"
libc = "0.2.98"
nix = "0.22.0"
notify = "4.0.17"

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false
