[package]
name = "trillium-cli"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/trillium-rs/trillium-cli"
keywords = ["trillium"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
ansi-to-html = "0.1.3"
async-channel = "1.8.0"
async-fs = "1.6.0"
async-global-executor = "2.3.1"
async-io = "1.13.0"
atty = "0.2.14"
blocking = "1.3.1"
broadcaster = "1.0.0"
env_logger = "0.10.0"
futures-lite = "1.13.0"
log = "0.4.17"
serde = "1.0.160"
serde_json = "1.0.96"
structopt = "0.3.26"
trillium = "0.2.9"
trillium-native-tls = "0.3.0"
trillium-rustls = "0.3.0"
trillium-proxy = "0.4.0"
trillium-router = "0.3.5"
trillium-static = { version = "0.4.0", features = ["smol"] }
trillium-websockets = { version = "0.5.1", features = ["json"] }
trillium-smol = "0.3.0"
trillium-client = "0.4.3"
trillium-logger = "0.4.2"
trillium-html-rewriter = "0.2.0"
url = "2.3.1"

[dependencies.bat]
features = ["atty", "clap", "dirs", "paging", "wild", "regex-onig"]
version = "0.23.0"
default-features = false

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.15"
libc = "0.2.142"
nix = "0.26.2"
notify = "5.1.0"

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false
