[package]
name = "trillium-cli"
version = "0.2.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "The trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/trillium-rs/trillium-cli"
keywords = ["trillium"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
ansi-to-html = "0.2.1"
async-channel = "2.1.1"
async-fs = "2.1.0"
async-global-executor = "2.4.1"
async-io = "2.2.2"
blocking = "1.5.1"
broadcaster = "1.0.0"
env_logger = "0.10.1"
futures-lite = "2.1.0"
log = "0.4.20"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
trillium = "0.2.11"
trillium-native-tls = "0.3.2"
trillium-rustls = "0.5.0"
trillium-proxy = "0.5.0"
trillium-router = "0.3.6"
trillium-static = { version = "0.4.1", features = ["smol"] }
trillium-websockets = { version = "0.6.0", features = ["json"] }
trillium-smol = "0.3.1"
trillium-client = { version = "0.4.9", features = ["json"] }
trillium-logger = "0.4.4"
trillium-html-rewriter = "0.3.0"
url = "2.5.0"
clap = { version = "4.4.13", features = ["derive", "env"] }
clap-verbosity-flag = "2.1.1"
colored = "2.1.0"
colored_json = "4.1.0"
mime = "0.3.17"
size = "0.4.1"
trillium-server-common = "0.4.7"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.17"
libc = "0.2.151"
nix = { version = "0.27.1", default-features = false, features = ["signal", "process"] }
notify = "6.1.1"

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false

[profile.release]
lto = "fat"
