[package]
name = "trillium-cli"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/trillium-rs/trillium-cli"
keywords = ["trillium"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
ansi-to-html = "0.1.3"
async-channel = "2.1.0"
async-fs = "2.1.0"
async-global-executor = "2.3.1"
async-io = "2.2.0"
atty = "0.2.14"
blocking = "1.5.1"
broadcaster = "1.0.0"
env_logger = "0.10.1"
futures-lite = "2.0.1"
log = "0.4.20"
serde = "1.0.193"
serde_json = "1.0.108"
trillium = "0.2.11"
trillium-native-tls = "0.3.0"
trillium-rustls = "0.4.0"
trillium-proxy = "0.4.2"
trillium-router = "0.3.5"
trillium-static = { version = "0.4.0", features = ["smol"] }
trillium-websockets = { version = "0.5.2", features = ["json"] }
trillium-smol = "0.3.1"
trillium-client = "0.4.6"
trillium-logger = "0.4.3"
trillium-html-rewriter = "0.3.0"
url = "2.5.0"
clap = { version = "4.4.8", features = ["derive", "env"] }
clap-verbosity-flag = "2.1.0"

[dependencies.bat]
features = ["minimal-application"]
version = "0.24.0"
default-features = false

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.17"
libc = "0.2.150"
nix = { version = "0.27.1", default-features = false, features = ["signal", "process"] }
notify = "6.1.1"

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false
