[package]
name = "trillium-cli"
version = "0.3.3"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "The trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/trillium-rs/trillium-cli"
keywords = ["trillium"]
categories = ["web-programming::http-server", "web-programming"]

[features]
default = ["serve", "client", "proxy", "rustls"]
serve = [
  "dep:trillium",
  "dep:trillium-logger",
  "dep:trillium-static",
  "dep:trillium-proxy",
  "dep:trillium-client",
]
dev-server = [
  "dep:ansi-to-html",
  "dep:async-io",
  "dep:broadcaster",
  "dep:futures-lite",
  "dep:serde",
  "dep:serde_json",
  "dep:trillium",
  "dep:trillium-proxy",
  "dep:trillium-router",
  "dep:trillium-client",
  "dep:trillium-websockets",
  "dep:trillium-html-rewriter",
  "dep:notify",
  "dep:nix",
  "dep:signal-hook",
  "dep:libc",
]
client = [
  "dep:async-fs",
  "dep:blocking",
  "dep:futures-lite",
  "dep:serde_json",
  "dep:trillium-client",
  "dep:colored",
  "dep:colored_json",
  "dep:mime",
  "dep:size",
]
proxy = [
  "dep:trillium",
  "dep:trillium-proxy",
  "dep:trillium-logger",
  "dep:trillium-client",
]
native-tls = ["dep:trillium-native-tls"]
rustls = ["dep:trillium-rustls"]

[dependencies]
ansi-to-html = { version = "0.2.1", optional = true }
async-fs = { version = "2.1.1", optional = true }
async-global-executor = "2.4.1"
async-io = { version = "2.3.1", optional = true }
blocking = { version = "1.5.1", optional = true }
broadcaster = { version = "1.0.0", optional = true }
env_logger = "0.10.2"
futures-lite = { version = "2.2.0", optional = true }
log = "0.4.20"
serde = { version = "1.0.196", features = ["derive"], optional = true }
serde_json = { version = "1.0.113", optional = true }
trillium = { version = "0.2.16", optional = true }
trillium-native-tls = { version = "0.3.2", optional = true }
trillium-rustls = { version = "0.6.0", optional = true }
trillium-proxy = { version = "0.5.2", optional = true }
trillium-router = { version = "0.3.6", optional = true }
trillium-static = { version = "0.4.1", features = ["smol"], optional = true }
trillium-websockets = { version = "0.6.3", features = [
  "json",
], optional = true }
trillium-smol = "0.3.3"
trillium-client = { version = "0.5.6", features = ["json"], optional = true }
trillium-logger = { version = "0.4.4", optional = true }
trillium-html-rewriter = { version = "0.3.0", optional = true }
clap = { version = "4.5.0", features = ["derive", "env"] }
clap-verbosity-flag = "2.1.2"
colored = { version = "2.1.0", optional = true }
colored_json = { version = "4.1.0", optional = true }
mime = { version = "0.3.17", optional = true }
size = { version = "0.4.1", optional = true }

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.3.17", optional = true }
libc = { version = "0.2.153", optional = true }
nix = { version = "0.27.1", default-features = false, features = [
  "signal",
  "process",
], optional = true }
notify = { version = "6.1.1", optional = true }

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false

[profile.release]
lto = "fat"
