[package]
name = "trillium-cli"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
description = "the trillium.rs cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
repository = "https://github.com/trillium-rs/trillium-cli"
keywords = ["trillium"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
ansi-to-html = "0.1.0"
async-channel = "1.6.1"
async-fs = "1.5.0"
async-global-executor = "2.0.2"
async-io = "1.6.0"
atty = "0.2.14"
blocking = "1.1.0"
broadcaster = "1.0.0"
env_logger = "0.9.0"
futures-lite = "1.12.0"
log = "0.4.14"
serde = "1.0.130"
serde_json = "1.0.72"
structopt = "0.3.25"
trillium = "0.2.2"
trillium-native-tls = "0.1.0"
trillium-rustls = "0.1.0"
trillium-proxy = "0.2.0"
trillium-router = "0.3.0"
trillium-static = { version = "0.4.0", features = ["smol"] }
trillium-websockets = { version = "0.4.0", features = ["json"] }
trillium-smol = "0.2.0"
trillium-client = "0.2.0"
trillium-logger = "0.4.0"
trillium-html-rewriter = "0.2.0"
url = "2.2.2"

[dependencies.bat]
version = "0.18.3"
default-features = false
features = [
  "atty",
  "clap",
  "dirs-next",
  "lazy_static",
  "paging",
  "wild",
  "regex-onig",
]

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.12"
libc = "0.2.109"
nix = "0.23.0"
notify = "4.0.17"

[lib]
doc = false

[[bin]]
name = "trillium"
doc = false
