name: CI

on:
  pull_request:
  push:
    branches:
      - main

# env:
#   RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        rust: [nightly, stable]
    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.29.6
    - name: Install NASM for aws-lc-rs on Windows
      if: runner.os == 'Windows'
      uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@master
    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features

  check_fmt_and_docs:
    name: Lints and Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format
      run: cargo fmt -- --check

    - name: Docs
      run: cargo doc --no-deps --all-features
